# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - uses: swift-actions/setup-swift@v2
      with:
        swift-version: "6"
    - name: Build
      run: swift build -c release
    - name: Archive binary
      uses: actions/upload-artifact@v4
      with:
        name: bear-to-ghost-${{ matrix.os }}
        path: |
          .build/release/bear-to-ghost
